src/api/__init__.py
# src/api/schemas/__init__.py

from flask import Blueprint
from flask_restful import Api

api_bp = Blueprint('api_bp', __name__)

api = Api(api_bp)

from src.api import routes

src/api/resources/__init__.py
# src/resources/__init__.py

src/api/routes.py
from src.api import api

from src.api.resources.departments import DepartmentListApi
from src.api.resources.employees import EmployeeListApi

api.add_resource(DepartmentListApi, '/api/departments', '/api/departments/<uuid>', strict_slashes=False)
api.add_resource(EmployeeListApi, '/api/employees', '/api/employees/<uuid>', strict_slashes=False)

src/api/schemas/__init__.py
# src/schemas/__init__.py

src/web_application/department/__init__.py
# src/web_application/department/__init__.py

from flask import Blueprint

department_bp = Blueprint('department_bp', __name__)

from src.web_application.department import views

src/web_application/department/views.py
# src/web_application/department/views.py

from flask import (render_template, flash, url_for,
                   redirect, request, abort)

from src.web_application.department import department_bp
from src.web_application.forms import DepartmentForm
from src.services.department import DepartmentService


# display the department(s)
@department_bp.route('/departments')
@department_bp.route('/departments/<string:uuid>')
def display_departments(uuid=None):
    """View function for departments:

    - display page of list of departments;
    - display page of department by uuid.
    """
    if uuid:
        department = DepartmentService.get_by_uuid(uuid)
        if not department:
            abort(404)
        avg_salary = DepartmentService.avg_salary(uuid)
        return render_template('department.html', department=department, avg_salary=avg_salary)
    departments = DepartmentService.get_all()
    avg_salary = DepartmentService.avg_salary
    return render_template('all_departments.html', departments=departments, avg_salary=avg_salary)


# create  a department
@department_bp.route('/create_department', methods=["POST", "GET"])
def create_department():
    """ View function for create department. """
    form = DepartmentForm()
    if form.validate_on_submit():
        department_data = {
            'name': request.form.get('name'),
            'description': request.form.get('description')
        }
        department = DepartmentService.create_obj(department_data)
        DepartmentService.save_to_db(department)
        flash('Department created successfully')
        return redirect(url_for('department_bp.display_departments', uuid=department.uuid))
    return render_template('department_form.html', form=form, page='create')


# update the department
@department_bp.route('/departments/<string:uuid>/update', methods=["POST", "GET"])
def update_department(uuid):
    """ View function for update department. """
    department = DepartmentService.get_by_uuid(uuid)
    if not department:
        abort(404)
    form = DepartmentForm(obj=department)
    if form.validate_on_submit():
        department.name = form.name.data
        department.description = form.description.data
        DepartmentService.save_to_db(department)
        flash('Department updated successfully')
        return redirect(url_for('department_bp.display_departments', uuid=department.uuid))
    return render_template('department_form.html', form=form, page='update')


@department_bp.route('/departments/<string:uuid>/del', methods=["POST", "GET"])
def del_department(uuid):
    """ View function for delete department. """
    department = DepartmentService.get_by_uuid(uuid)
    if not department:
        abort(404)
    if department.department_employees:
        flash('You cannot delete department with the employees')
        return redirect(url_for('department_bp.display_departments', uuid=department.uuid))
    DepartmentService.delete_from_db(department)
    flash('department deleted successfully')
    return redirect(url_for('department_bp.display_departments'))

src/web_application/employee/__init__.py
# src/web_application/employee/__init__.py

from flask import Blueprint

employee_bp = Blueprint('employee_bp', __name__)

from src.web_application.employee import views

src/web_application/employee/views.py
# src/web_application/employee/views.py

from flask import (render_template, url_for,
                   redirect, abort, flash)

from src.web_application.employee import employee_bp

from src.web_application.forms import EmployeeForm, EmployeeSearchForm
from src.services.department import DepartmentService
from src.services.employee import EmployeeService


# display the employee(s)
@employee_bp.route('/employees/<string:uuid>', methods=["GET", "POST"])
@employee_bp.route('/employees', methods=["GET", "POST"])
def display_employees(uuid=None):
    """View function for employees:

    - display page of list of employees, form for search of employess by birth date;
    - display page of employee by uuid.
    """
    if uuid:
        employee = EmployeeService.get_by_uuid(uuid)
        if not employee:
            abort(404)
        department = DepartmentService.get_by_uuid(employee.department_uuid)
        return render_template('employee.html', employee=employee, department=department)
    form = EmployeeSearchForm()
    if form.validate_on_submit():
        start_date = form.start_date.data
        end_date = form.end_date.data
        return redirect(url_for('employee_bp.search_by_bd', start_date=start_date, end_date=end_date))
    employees = EmployeeService.get_all()
    return render_template('all_employees.html', employees=employees, form=form)


# Search employee by birth date
@employee_bp.route('/employees/search_results/<start_date>')
@employee_bp.route('/employees/search_results/<start_date>/<end_date>')
def search_by_bd(start_date, end_date=None):
    """ View function for display page with search result of  employees by birth date. """
    employees = EmployeeService.search_employee(start_date, end_date)
    return render_template(
        'employee_search_results.html',
        employees=employees, start_date=start_date, end_date=end_date
    )


# create employee
@employee_bp.route('/create_employee', methods=["POST", "GET"])
def create_employee():
    """ View function for create employee. """
    form = EmployeeForm()
    if form.validate_on_submit():
        employee_data = {
            'employee_name': form.employee_name.data,
            'birth_date': form.birth_date.data,
            'salary': form.salary.data,
            'department_uuid': form.department_uuid.data
        }
        department = DepartmentService.get_by_uuid(form.department_uuid.data)
        if department:
            employee = EmployeeService.create_obj(employee_data)
            EmployeeService.save_to_db(employee)
            flash('Employee created successfully')
            return redirect(url_for('employee_bp.display_employees', uuid=employee.uuid))
        flash('input the correct uuid of the department')
    return render_template('employee_form.html', form=form, page='create')


# update the employee
@employee_bp.route('/employees/<string:uuid>/update', methods=["POST", "GET"])
def update_employee(uuid):
    """ View function for update employee. """
    employee = EmployeeService.get_by_uuid(uuid)
    if not employee:
        abort(404)
    form = EmployeeForm(obj=employee)
    if form.validate_on_submit():
        employee.employee_name = form.employee_name.data
        employee.birth_date = form.birth_date.data
        employee.salary = form.salary.data
        employee.department_uuid = form.department_uuid.data
        department = DepartmentService.get_by_uuid(employee.department_uuid)
        if department:
            EmployeeService.save_to_db(employee)
            flash('Employee updated successfully')
            return redirect(url_for('employee_bp.display_employees', uuid=employee.uuid))
        flash('input the correct uuid of the department')
    return render_template('employee_form.html', form=form, page='update')


# delete the employee
@employee_bp.route('/employees/<string:uuid>/delete', methods=["POST", "GET"])
def del_employee(uuid):
    """ View function for delete employee. """
    employee = EmployeeService.get_by_uuid(uuid)
    if not employee:
        abort(404)
    EmployeeService.delete_from_db(employee)
    flash('employee deleted successfully')
    return redirect(url_for('employee_bp.display_employees'))

src/templates/all_departments.html
{% extends 'base.html' %}
{% block title %}Departments{% endblock %}
{% block content %}
    <div class="p-3 mb-2 bg-light text-dark"">
        <h4>Company Departments:</h4>
        <ul>
            {% for department in departments %}
                <li>
                    <a href="{{ url_for('department_bp.display_departments', uuid=department.uuid) }}">{{ department.name }}</a>
                    <p>Average annual salary: {{ avg_salary(department.uuid) }} USD</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

src/templates/all_employees.html
{% extends 'base.html' %}
{% block title %}Employees{% endblock %}
{% block content %}
    <div class="p-3 mb-2 bg-light text-dark">
    <h6>Search employee by birth date:</h6>
        <form  method="POST">
        <ul class="nav">

        <li class="nav-link">
            {{ form.hidden_tag() }}
        </li>
        <li class="nav-link">
            {{ form.start_date.label(class="form-control-label") }}
            {{ form.start_date(class="form-control form-control-lg", placeholder="year-month-day")}}
        </li>
        <li class="nav-link">
            {{ form.end_date.label(class="form-control-label") }}
            {{ form.end_date(class="form-control form-control-lg", placeholder="year-month-day")}}
        </li>
        <li class="nav-link">
            <br>
            {{ form.submit(class="form-control form-control-lg") }}
        </li>

        </ul>
        </form>
    </div>
    <div class="p-3 mb-2 bg-light text-dark">
        <h4>Company Employees:</h4>
        <ul>
            {% for employee in employees %}
                <li>
                    <a href="{{ url_for('employee_bp.display_employees', uuid=employee.uuid) }}">{{ employee.employee_name }}</a>
                    <p>Annual salary: {{ employee.salary }} USD</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

src/templates/api.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock %}
{% block content %}
    <div class="p-3 mb-2 bg-light text-dark">
        <h4>Api rest service</h4>
    <hr>
    <h6>REST API service for third-party developers has 2 resources: </h6>
    <h6>1) Departments:</h6>
    <p>1.1. access to the collection of the departments of the company:</p>
    <p>base-url<span style="color: #2330ff">/api/departments/</span> - method get</p>
    <p>1.2. access to the department by its uuid:</p>
    <p>base-url<span style="color: #2330ff">/api/departments/uuid</span>  - methods get, post, put, delete</p>
    <h6>2) Employees:</h6>
    <p>2.1. access to the collection of the employees of the company:</p>
    <p>base-url<span style="color: #2330ff">/api/employees/</span> - method get</p>
    <p>2.2. access to the employee by its uuid:</p>
    <p>base-url<span style="color: #2330ff">/api/employees/uuid</span>  - methods get, post, put, delete</p>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
<body>
    <div class="container">
    <ul class="nav">
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Home</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('department_bp.display_departments') }}">Departments</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('department_bp.create_department') }}">Add department</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('employee_bp.display_employees') }}">Employees</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('employee_bp.create_employee') }}">Add employee</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('core.api') }}">API</a>
        </li>
    </ul>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li style="color:red">message: {{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block content %}

    {% endblock %}
    </div>
</body>
</html>

src/templates/department.html
{% extends 'base.html' %}
{% block title %}Department{% endblock %}
{% block content %}
    <div class="p-3 mb-2 bg-light text-dark"">
        <h1>{{department.name}}</h1>
        {% if department.description %}
            <h6>Description: {{ department.description }}</h6>
        {% else %}
            <p>Description is absent now.</p>
        {% endif %}
        <h6>uuid: <span style="color: red">{{ department.uuid }}</span></h6>
        <h4>Average salary: {{ avg_salary }} USD per year.</h4>
        <hr>
        {% if department.department_employees %}
            <h4>List of employees:</h4>
            <ul>
                {% for employee in department.department_employees %}
                    <li>
                        <a href="{{ url_for('employee_bp.display_employees', uuid=employee.uuid) }}">{{ employee.employee_name }}</a>
                        <p>Annual salary: {{ employee.salary }} USD</p>

                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h6>There is no employees in the department now.</h6>
        {% endif %}
        <hr>
        <p></p>
        <a href="{{ url_for('employee_bp.create_employee', uuid=department.uuid) }}">Add Employee</a>
        <p></p>
        <a href="{{ url_for('department_bp.update_department', uuid=department.uuid) }}">Update department</a>
        <p></p>
    <a href="{{ url_for('department_bp.del_department', uuid=department.uuid) }}"><p style="color: red" >Delete department</p></a>
    </div>
{% endblock %}

src/templates/department_form.html
{% extends 'base.html' %}
{% block title %}Department{% endblock %}
{% block content %}
    <div class="container">
    {% if page == 'create' %}
        <h4>Add department page.</h4>
    {% elif page == 'update' %}
        <h4>Update department page.</h4>
    {% endif %}
    <form class="form-group" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label(class="form-control-label") }}
            {{ form.name(class="form-control form-control-lg")}}
        </div>
        <div class="form-group">
            {{ form.description.label(class="form-control-label") }}
            {{ form.description(class="form-control form-control-lg")}}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>
{% endblock %}

src/templates/employee.html
{% extends 'base.html' %}
{% block title %}Employee{% endblock %}
{% block content %}
    <div class="p-3 mb-2 bg-light text-dark">
        <h4>Employee: {{ employee.employee_name }}</h4>
        <p>Date of birth: {{ employee.birth_date }}</p>
        <p>Salary: {{ employee.salary }} USD per year.</p>
        <p>Department: <a href="{{ url_for('department_bp.display_departments', uuid=employee.department_uuid) }}">{{ department.name }}</a></p>
        <a href="{{ url_for('employee_bp.update_employee', uuid=employee.uuid) }}"><p>Update employee</p></a>
        <a href="{{ url_for('employee_bp.del_employee', uuid=employee.uuid) }}"><p style="color:red">Delete employee</p></a>
    </div>
{% endblock %}

{# add button for delete and update the employee #}

src/templates/employee_form.html
{% extends 'base.html' %}
{% block title %}Employee{% endblock %}
{% block content %}
    <div class="container">
        {% if page == 'create' %}
            <h4>Add employee page.</h4>
        {% elif page == 'update' %}
            <h4>Update employee page.</h4>
        {% endif %}
        <p></p>
        <form class="form-group" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.employee_name.label(class="form-control-label") }}
                {{ form.employee_name(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.birth_date.label(class="form-control-label") }}
                {{ form.birth_date(class="form-control form-control-lg", placeholder="year-month-day")}}
            </div>
            <div class="form-group">
                {{ form.salary.label(class="form-control-label") }}
                {{ form.salary(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.department_uuid.label(class="form-control-label") }}
                {{ form.department_uuid(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>

    </div>
{% endblock %}

src/templates/employee_search_form.html
{% extends 'base.html' %}
{% block title %}Employee Search{% endblock %}
{% block content %}
    <div class="container">
        <p></p>
        <h6>Employee search by birth date:</h6>
        <p>Please fill form below, </p>
        <p>you may input only start date and search the employees that were born  </p>
        <p>on the certain date or input start and end dates andd search for the employees </p>
        <p>that were born in the period between dates</p>
        <p></p>
        <form class="form-group" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.start_date.label(class="form-control-label") }}
                {{ form.start_date(class="form-control form-control-lg", placeholder="year-month-day")}}
            </div>
            <div class="form-group">
                {{ form.end_date.label(class="form-control-label") }}
                {{ form.end_date(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

src/templates/employee_search_results.html
{% extends 'base.html' %}
{% block title %}Employees{% endblock %}
{% block content %}
    <div class="p-3 mb-2 bg-light text-dark">
    <h6>SEARCH RESULT:</h6>
    {% if end_date %}
        <p style="color: green">List of the employees that were born between {{ start_date }} and {{ end_date }}:</p>
    {% else %}
        <p style="color: green">List of the employees that were born on {{ start_date }}:</p>
    {% endif %}

    {% if employees %}
        <ul>
        {% for employee in employees %}
            <li>
                <a href="{{ url_for('employee_bp.display_employees', uuid=employee.uuid) }}">{{ employee.employee_name }}</a>
                <p>birth date: {{ employee.birth_date }}</p>
            </li>
        {% endfor %}
        </ul>

    {% else %}
        <p style="color: red">There is no employees according to your request.</p>
    {% endif %}
    </div>
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock %}
{% block content %}
    <div class="p-3 mb-2 bg-light text-dark"">
        <h4>Global Pharma Trade LLC.</h4>
    <hr>
    <br>
    <p>We reliably supply markets in Eastern Europe with active pharmaceutical ingredients (API)</p>
    <p>for veterinary and human medicinal products. For over ten years,</p>
    <p> “Global Pharma Trade LLC.“ has been trading successfully at an international level.</p>
    <p> The company has a clear-cut philosophy: a prompt service, reliability and precision.</p>
    <p>Thanks to our high-performance partner company “Global Pharma Trade LLC.”,
    <p>we are in a position to constantly guarantee the highest product quality – always at a fair rate.</p>
    </div>
{% endblock %}